### ISSUE TITLE
function mz_calculate_transit_routes(bigint) does not exist

### ISSUE THREAD

**Issue by oleksii-zavrazhnyi** [mapzen/vagrant-tiles#3]
Steps to reproduce:
1) Cook vagrant
2) run `vagrant up`
3) run `vagrant ssh`
4) run `sudo apt-get install curl`
5) run `curl http://localhost/osm/buildings/16/19293/24641.json`

Expected result:
See correct server response

Actual result:
Got "Internal Server Error"

`cat /var/log/tileserver/current`

```
2016-02-09_01:03:19.95254 2016-02-09 01:03:19 [6104] [INFO] Starting gunicorn 17.5                                                                                                   
2016-02-09_01:03:19.95464 2016-02-09 01:03:19 [6104] [INFO] Listening at: unix:/var/run/tileserver/gunicorn.socket (6104)                                                            
2016-02-09_01:03:19.95476 2016-02-09 01:03:19 [6104] [INFO] Using worker: gevent                                                                                                     
2016-02-09_01:03:19.95767 2016-02-09 01:03:19 [6118] [INFO] Booting worker with pid: 6118                                                                                            
2016-02-09_01:03:20.00834 2016-02-09 01:03:19 [6119] [INFO] Booting worker with pid: 6119                                                                                            
2016-02-09_01:03:20.07034 2016-02-09 01:03:20 [6121] [INFO] Booting worker with pid: 6121                                                                                            
2016-02-09_01:03:20.15867 2016-02-09 01:03:20 [6125] [INFO] Booting worker with pid: 6125                                                                                            
2016-02-09_01:03:20.21517 2016-02-09 01:03:20 [6128] [INFO] Booting worker with pid: 6128                                                                                            
2016-02-09_01:04:04.20532 2016-02-09 01:04:04 [6104] [INFO] Handling signal: term                                                                                                    
2016-02-09_01:04:04.20558 2016-02-09 01:04:04 [6118] [INFO] Worker exiting (pid: 6118)                                                                                               
2016-02-09_01:04:04.20560 2016-02-09 01:04:04 [6121] [INFO] Worker exiting (pid: 6121)                                                                                               
2016-02-09_01:04:04.20650 2016-02-09 01:04:04 [6125] [INFO] Worker exiting (pid: 6125)                                                                                               
2016-02-09_01:04:04.20651 2016-02-09 01:04:04 [6128] [INFO] Worker exiting (pid: 6128)                                                                                               
2016-02-09_01:04:04.20735 2016-02-09 01:04:04 [6119] [INFO] Worker exiting (pid: 6119)                                                                                               
2016-02-09_01:04:04.52631 2016-02-09 01:04:04 [6104] [INFO] Shutting down: Master                                                                                                    
2016-02-09_01:04:04.92258 2016-02-09 01:04:04 [9934] [INFO] Starting gunicorn 17.5                                                                                                   
2016-02-09_01:04:04.93388 2016-02-09 01:04:04 [9934] [INFO] Listening at: unix:/var/run/tileserver/gunicorn.socket (9934)                                                            
2016-02-09_01:04:04.93401 2016-02-09 01:04:04 [9934] [INFO] Using worker: gevent                                                                                                     
2016-02-09_01:04:04.94101 2016-02-09 01:04:04 [9996] [INFO] Booting worker with pid: 9996                                                                                            
2016-02-09_01:04:05.01423 2016-02-09 01:04:05 [10002] [INFO] Booting worker with pid: 10002                                                                                          
2016-02-09_01:04:05.05487 2016-02-09 01:04:05 [10004] [INFO] Booting worker with pid: 10004                                                                                          
2016-02-09_01:04:05.13555 2016-02-09 01:04:05 [10006] [INFO] Booting worker with pid: 10006                                                                                          
2016-02-09_01:04:05.30940 2016-02-09 01:04:05 [10015] [INFO] Booting worker with pid: 10015                                                                                          
2016-02-09_06:42:19.15991 Error handling request for /buildings/16/19293/24641.json: Traceback (most recent call last): |   File "/usr/local/lib/python2.7/dist-packages/tileserver/_
_init__.py", line 187, in __call__    response = self.handle_request(request) |   File "/usr/local/lib/python2.7/dist-packages/tileserver/__init__.py", line 274, in handle_request  
  feature_data_all = self.data_fetcher(coord, self.layer_config.all_layers) |   File "/usr/local/lib/python2.7/dist-packages/tilequeue/query.py", line 195, in __call__    raise asyn
c_exception | ProgrammingError: function mz_calculate_transit_routes(bigint) does not existLINE 33:         THEN mz_calculate_transit_routes(osm_id)                      ^HINT:  No 
function matches the given name and argument types. You might need to add explicit type casts.                                                                                       
2016-02-09_06:42:19.22438 ::1 - - [09/Feb/2016:06:42:19] "GET /buildings/16/19293/24641.json HTTP/1.0" 500 21 "-" "curl/7.35.0"                                                      
```

**Comment by nvkelso** [comment]
We're looking into this, but it'll probably be next week before we get you more info. You might try a berks update in the meantime?

**Comment by nvkelso** [comment]
More background, duplicated from Rob and your email:

> The vagrant-tiles repo has lagged behind a little bit in terms of the setup. It's likely that it just needs some more work to get it back into shape. The instructions in the [vector-datasource repo wiki](https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service) should be up to date though and let you get a working development rig, modulo that [tileserver issue](https://github.com/mapzen/tileserver/issues/15).

**Comment by rmarianski** [comment]
Can you confirm that it still doesn't work for you? I gave this a try with a new image using vagrant up, and it seems like it worked. I got an error saying that the tilequeue restart failed, but it looks like it was due to a timeout rather than a different error. The tilequeue processor is running and generating tiles, and the curl command does yield a tile for me.

It's possible that we didn't have the initial sql functions set up correctly when you tried this last time, but it looks like those got fixed along the way. Mind giving it another shot with a fresh image?

**Comment by oleksii-zavrazhnyi** [comment]
It works right now, I'm feeling strange...

**Comment by rmarianski** [comment]
A good strange? :)

I'll close this for now, but please re-open if you notice another failure. And thanks for reporting this in the first place!

**Comment by oleksii-zavrazhnyi** [comment]
Yes it is, you that strange feeling, when you do nothing and everything magically went fixed :)
